# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/k4minashi/app_0:1.0 .
      - run: docker push ghcr.io/k4minashi/app_0:1.0
  install:
    runs-on: unbuntu-latest
    needs: [build]
    steps:
      - name: inst
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/k4minashi/app_0:1.0
      - run: docker run ghcr.io/k4minashi/app_0:1.0
          
          
