# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/k4minashi/app_0:1.0 .
      - run: docker push ghcr.io/k4minashi/app_0:1.0
      - run: ssh -o "StrictHostKeyChecking no" 'k4minashi-0712-oq5w2dnwide@k4minashi-0712-oq5w2dnwide.ssh.ws-eu106.gitpod.io' 'cd /workspace/07.12 && docker compose pull && docker compose up -d'
